### ISSUE TITLE
Registeel #378 is in pvp list

### ISSUE THREAD

**Issue by Fabio1988** [na-ji/pvpoke-to-poracle#5]
There are legendaries again in the tracking list, they can't spawn, did anything change? :) 

https://github.com/na-ji/pvpoke-to-poracle/commit/19d6e1892d15c1ee85b981435006c5eaa14f7f5c

**Comment by na-ji** [comment]
Yeah, the change I did was to not count them in the 30 limit. So yes they are still there, but there are also 30 non legendaries in each list. I made this choice because legendaries might spawn every year during the tours events. For instance, for the Hoenn tour, the probability is really high that Latios and Latias are going to spawn.

**Comment by Fabio1988** [comment]
Ahh so the list is now longer than 30 elements, did not noticed, thank you
